// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * Hi {name}! Please leave a star if you like this project: https://github.com/jellydn/i18n-react-app
	 * @param {string} name
	 */
	Hello: RequiredParams<'name'>
}

export type TranslationFunctions = {
	/**
	 * Hi {name}! Please leave a star if you like this project: https://github.com/jellydn/i18n-react-app
	 */
	Hello: (arg: { name: string }) => LocalizedString
}

export type Formatters = {}
